### PR TITLE
Add first draft of Storybook integration examples using Redwood tutorial

### PR DESCRIPTION
**Pull request by virtuoushub**
---

cc @yannbf

### CODE REVIEW

**Comment by yannbf** [comment]
@virtuoushub it would be super nice if you deployed the storybook as well! 

You could easily do that with chromatic


Or you could do it with netlify as well. My sample project does that in vercel, netlify and chromatic! It's open source and you can check if it helps.

Here's how I do with netlify:

I create a build-all command: https://github.com/yannbf/mealdrop/blob/0ef0fb2be3c89612a752289de7526f48991ee3b2/package.json#L30

Then I setup my build command in netlify to be that

Then I add this redirects config https://github.com/yannbf/mealdrop/blob/0ef0fb2be3c89612a752289de7526f48991ee3b2/public/_redirects#L1

So the app is accessible at 

https://mealdrop.netlify.app

And storybook is accessible at 

https://mealdrop.netlify.app/storybook

**Comment by thedavidprice** [comment]
🚀

**Comment by thedavidprice** [comment]
FYI I think Redwood already includes the build command for SB:
`yarn rw sb --build` should do it

**Comment by virtuoushub** [comment]
> @virtuoushub it would be super nice if you deployed the storybook as well!

Quick follow up in case it helps others; this was done via #11 

secret sauce was this: https://github.com/redwoodjs/example-storybook/blob/def0a0de0aa40483f065053f3fc87f362e7c5857/netlify.toml#L2-L5

I also just avoided doing prisma's schema / data migration steps because it kept failing in CI/CD

At some point I will circle back and make that work; but it works well enough as is to get the Storybook example out.

**Pull request merged**
